apiVersion: scheduler.kalypso.io/v1alpha1
kind: BaseRepo
metadata:
  name: main
spec:
  repo: https://github.com/kshitijcode/kalypso-sharmaks-v15-control-plane
  branch: main
  path: .
  commit: bb20697fd416c0206e3ddadac9e73a867306c84e
